# Generated by Django 5.0.1 on 2024-01-29 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=2021, message="Choose year after 2021."
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=2024,
                                message="Choose valid year less than or equal to 2024",
                            ),
                        ]
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Title can only contain letters, numbers, spaces, hyphens, and underscores.",
                                regex="^[a-zA-Z0-9\\s\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=2500,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=50,
                                message="Project description should be at least 50 characters long.",
                            )
                        ],
                    ),
                ),
                ("build_with", models.CharField(max_length=300)),
                (
                    "project_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.URLValidator(),
                            django.core.validators.MinLengthValidator(
                                limit_value=7,
                                message="Project link must be at least 7 characters long.",
                            ),
                        ],
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        unique=True,
                        validators=[
                            django.core.validators.URLValidator(),
                            django.core.validators.MinLengthValidator(
                                limit_value=7,
                                message="GitHub link must be at least 7 characters long.",
                            ),
                        ],
                    ),
                ),
            ],
        ),
    ]
