# Generated by Django 5.0.1 on 2024-02-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_year_project_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
