# Generated by Django 5.0.1 on 2024-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0012_alter_education_options_and_more"),
        ("projects", "0003_alter_project_options_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="build_with",
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, to="experience.technology", verbose_name="Technologies"
            ),
        ),
    ]
