# Generated by Django 5.0.1 on 2024-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_build_with_project_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_image",
            field=models.ImageField(null=True, upload_to="images/projects/"),
        ),
    ]
