# Generated by Django 5.0.1 on 2024-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/projects/"
            ),
        ),
    ]
