# Generated by Django 5.0.1 on 2024-01-30 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 30, 7, 33, 25, 24918, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
