# Generated by Django 5.0.1 on 2024-01-30 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 30, 10, 31, 58, 855196, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
