# Generated by Django 5.0.1 on 2024-02-03 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_alter_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 3, 17, 33, 10, 589471, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
