# Generated by Django 5.0.1 on 2024-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0006_alter_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
