# Generated by Django 5.0.1 on 2024-01-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_aboutpagecontent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutpagecontent",
            old_name="introduction",
            new_name="about",
        ),
    ]
