# Generated by Django 5.0.1 on 2024-01-30 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_introduction_aboutpagecontent_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="cv",
            field=models.FileField(upload_to="files/"),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="github_link",
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="linkedin_link",
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="phone_number",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="First name can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Last name can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="First name can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Last name can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
    ]
