# Generated by Django 5.0.1 on 2024-02-03 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_homepagecontent_cv_homepagecontent_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="last_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="location",
            field=models.CharField(default="Sofia, Bulgaria", max_length=100),
        ),
    ]
