# Generated by Django 5.0.1 on 2024-02-03 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_homepagecontent_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagecontent",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="last_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="last_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
