# Generated by Django 5.0.1 on 2024-02-05 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_aboutpagecontent_creation_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutpagecontent",
            old_name="creation_date",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="aboutpagecontent",
            old_name="last_update",
            new_name="updated_on",
        ),
        migrations.RenameField(
            model_name="homepagecontent",
            old_name="creation_date",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="homepagecontent",
            old_name="last_update",
            new_name="updated_on",
        ),
    ]
