# Generated by Django 5.0.1 on 2024-02-05 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_creation_date_aboutpagecontent_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="github_link",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()],
                verbose_name="GitHub",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="linkedin_link",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()],
                verbose_name="LinkedIn",
            ),
        ),
    ]
