# Generated by Django 5.0.1 on 2024-02-05 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_homepagecontent_github_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="about",
            field=models.TextField(verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="created_on",
            field=models.DateField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Surname can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
                verbose_name="Surname",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="profession",
            field=models.CharField(max_length=70, verbose_name="Profession"),
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="updated_on",
            field=models.DateField(auto_now=True, verbose_name="Last update"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="created_on",
            field=models.DateField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="cv",
            field=models.FileField(upload_to="staticfiles/files/", verbose_name="CV"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="introduction",
            field=models.TextField(verbose_name="Introduction"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Surname can only contain letters and spaces.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
                verbose_name="Surname",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="phone_number",
            field=models.CharField(verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="profession",
            field=models.CharField(max_length=70, verbose_name="Profession"),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="updated_on",
            field=models.DateField(auto_now=True, verbose_name="Last update"),
        ),
    ]
