# Generated by Django 5.0.1 on 2024-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0008_alter_education_name"),
        ("main", "0009_alter_aboutpagecontent_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="skills",
            field=models.ManyToManyField(to="experience.skill", verbose_name="Skill"),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="technologies",
            field=models.ManyToManyField(
                to="experience.technology", verbose_name="Technologies"
            ),
        ),
    ]
