# Generated by Django 5.0.1 on 2024-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0008_alter_education_name"),
        ("main", "0010_homepagecontent_skills_homepagecontent_technologies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagecontent",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="technologies",
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="skills",
            field=models.ManyToManyField(to="experience.skill", verbose_name="Skills"),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="technologies",
            field=models.ManyToManyField(
                to="experience.technology", verbose_name="Technologies"
            ),
        ),
    ]
