# Generated by Django 5.0.1 on 2024-02-09 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_homepagecontent_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpagecontent",
            name="skills",
        ),
    ]
