# Generated by Django 5.0.1 on 2024-02-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_aboutpagecontent_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecontent",
            name="cv",
            field=models.FileField(upload_to="documents/cv/", verbose_name="CV"),
        ),
    ]
