# Generated by Django 5.0.1 on 2024-02-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "logo_svg",
                    models.TextField(blank=True, help_text="Paste your SVG code here."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("update_on", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                (
                    "logo_svg",
                    models.TextField(blank=True, help_text="Paste your SVG code here."),
                ),
                ("specialty", models.CharField(max_length=100)),
                (
                    "certificates",
                    models.ManyToManyField(blank=True, to="experience.certificate"),
                ),
                ("skills", models.ManyToManyField(blank=True, to="experience.skill")),
                ("technologies", models.ManyToManyField(to="experience.technology")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("update_on", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                (
                    "logo_svg",
                    models.TextField(blank=True, help_text="Paste your SVG code here."),
                ),
                ("title", models.CharField(max_length=100)),
                ("skills", models.ManyToManyField(blank=True, to="experience.skill")),
                ("technologies", models.ManyToManyField(to="experience.technology")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
