# Generated by Django 5.0.1 on 2024-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="education",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="experience.technology"),
        ),
        migrations.AlterField(
            model_name="work",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="experience.technology"),
        ),
    ]
