# Generated by Django 5.0.1 on 2024-02-05 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0002_alter_certificate_options_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="date",
            field=models.DateField(),
        ),
    ]
