# Generated by Django 5.0.1 on 2024-02-07 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0004_alter_certificate_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="update_on",
            new_name="updated_on",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="update_on",
            new_name="updated_on",
        ),
    ]
