# Generated by Django 5.0.1 on 2024-02-07 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0005_rename_update_on_education_updated_on_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="specialty",
            new_name="speciality",
        ),
    ]
