# Generated by Django 5.0.1 on 2024-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0007_alter_education_certificates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="name",
            field=models.CharField(
                max_length=50, verbose_name="School or university name"
            ),
        ),
    ]
