# Generated by Django 5.0.1 on 2024-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0009_alter_certificate_options_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AddField(
            model_name="work",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
