# Generated by Django 5.0.1 on 2024-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0012_alter_education_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="has_diploma",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Has diploma"
            ),
        ),
    ]
