# Generated by Django 5.0.1 on 2024-02-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0013_education_has_diploma"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Determines display order in the list"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["display_order"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="has_diploma",
        ),
        migrations.AddField(
            model_name="education",
            name="diploma",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="experience.diploma",
                verbose_name="Diploma",
            ),
        ),
    ]
