# Generated by Django 5.0.1 on 2024-02-23 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0014_diploma_remove_education_has_diploma_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diploma",
            options={},
        ),
        migrations.RemoveField(
            model_name="diploma",
            name="display_order",
        ),
        migrations.AddField(
            model_name="diploma",
            name="date",
            field=models.CharField()
        ),
    ]
